# Generated by Django 4.1.3 on 2022-11-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='seeding_pct',
            field=models.TextField(null=True),
        ),
    ]
