# Generated by Django 4.1.3 on 2022-12-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='OpenTime',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='PagePic',
            field=models.TextField(null=True),
        ),
    ]
